<?php
	session_start();
	if(!isset($_SESSION['loginUser'])){
		header("Location:loginPage.php");
	}else{
		if($_SESSION['loginUser']=='admin@gmail.com'){
			header("Location:adminHome.php");
		}
		else{
			header("Location:customerHome.php");
		}
	}
